parameters:
    network_file : 'data/biogrid_3.168_filtered.tsv'
    sp_matrix: "data/matrices/interactome_SP.hdf5"
    rwr_matrix: "data/matrices/interactome_RWR.hdf5"
    geneset_file: 'data/bailey.gmt'
    geneset_csv: 'data/bailey.gmt'
    outpath: 'results/multi/'
    diagnostic_folder: 'results/multi/'
    
topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 1
    cores: 1

association:
    analyse: []
    geneset_B : ''
    number_of_permutations: 1
    cores: 1

within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 1
    cores: 1

figures:
    extension: ['pdf', 'png']
    outpath: 'results/multi/'

hdn_parameters:
    number_simulations: 2
    n_nodes: 10
    network_probability: []
    hdn_probability: []
    hdn_percentage: []

sbm_parameters:
    number_simulations: 2
    n_nodes: 10
    theta0: ''
    percentage: ''
    density: ''
