parameters:
    network_file : 'data/barabasi.interactome.tsv'
    sp_matrix: "matrices/interactome_SP.hdf5"
    rwr_matrix: "matrices/interactome_RWR.hdf5"
    geneset_file: 'data/disgenet_cancer.gmt'
    outpath: 'results/pygna'
    
topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 50
    cores: 4
association:
    analyse: ['rwr', 'sp']
    geneset_B : 'data/disgenet_cancer.gmt'
    number_of_permutations: 50
    cores: 4
within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 50
    cores: 4

figures:
    extension: ['png']
    outpath: 'results/figures/pygna'