parameters:
    network_file : "data/biogrid_3.168_filtered.tsv"
    sp_matrix: "data/matrices/interactome_SP.hdf5"
    rwr_matrix: "data/matrices/interactome_RWR.hdf5"
    geneset_file: "data/blca_diffexp.gmt"
    geneset_csv: "data/blca_diffexp.csv"
    outpath: 'results/single_geneset/'
    diagnostic_folder: 'results/single_geneset/'

topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 1
    cores: 1

association:
    analyse: ['rwr', 'sp']
    geneset_B : 'data/goslimEntrez.gmt'
    number_of_permutations: 1
    cores: 1

within_comparison:
    analyse: []
    number_of_permutations: 1
    cores: 1

figures:
    extension: ['png', 'pdf']
    outpath: 'results/single_geneset/'

hdn_parameters:
    number_simulations: 2
    n_nodes: 10
    network_probability: []
    hdn_probability: []
    hdn_percentage: []

sbm_parameters:
    number_simulations: 2
    n_nodes: 10
    theta0: ''
    percentage: ''
    density: ''
