parameters:
    network_file: '../pygna_paper_proj/data/external/biogrid_3.168_filtered.tsv'
    sp_matrix: "../pygna_paper_proj/data/interactome_SP.hdf5"
    rwr_matrix: "../pygna_paper_proj/data/interactome_RWR.hdf5"
    geneset_file: '../pygna_paper_proj/data/external/bailey.gmt'
    diagnostic_folder: '../pygna_paper_proj/results/temp/figures/'
    outpath: '../pygna_paper_proj/results/temp/datasets/'
    tcga_dataset: ["tcga_brca", "tcga_prad", "tcga_lusc", "tcga_laml", "tcga_dlbc", "tcga_lcml"]

topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 100
    cores: 1

association:
    analyse: ['rwr', 'sp']
    geneset_B : ["tcga_brca", "tcga_prad", "tcga_lusc", "tcga_laml", "tcga_dlbc", "tcga_lcml"]
    number_of_permutations: 100
    cores: 1

within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 100
    cores: 1

figures:
    extension: ['png']
    outpath: 'figures/'
