parameters:
    network_file : '../min_working_example/barabasi.interactome.tsv'
    sp_matrix: "../min_working_example/matrices/interactome_SP.hdf5"
    rwr_matrix: "../min_working_example/matrices/interactome_RWR.hdf5"
    geneset_file: '../min_working_example/disgenet_cancer_groups_subset.gmt'
    outpath: '../min_working_example/results/'
    
topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 100
    cores: 4
association:
    analyse: ['rwr', 'sp']
    geneset_B : '../min_working_example/disgenet_cancer_groups_subset.gmt'
    number_of_permutations: 100
    cores: 4
within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 100
    cores: 4

figures:
    extension: ['png']
    outpath: '../min_working_example/results/figures/'