parameters:
    network_file: '<network_file.tsv>'
    sp_matrix: "<sp_matrix.hdf5>"
    rwr_matrix: "<rwr_matrix.hdf5>"
    geneset_file: '<geneset_file.gmt>'
    diagnostic_folder: '<diagnostic_files_folder>'
    outpath: '<output_folder>'

topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 2
    cores: 1

association:
    analyse: ['rwr', 'sp']
    geneset_B : <geneset_B.gmt>
    number_of_permutations: 2
    cores: 1

within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 2
    cores: 1

figures:
    extension: ['png','pdf']
    outpath: 'figures/'
