parameters:
    network_file : '../pygna_paper_proj/data/biogrid_3.168_filtered.tsv'
    sp_matrix: "../pygna_paper_proj/data/interactome_SP.hdf5"
    rwr_matrix: "../pygna_paper_proj/data/interactome_RWR.hdf5"
    geneset_file: '../pygna_paper_proj/data/bailey.gmt'
    geneset_csv: ''
    outpath: '../pygna_paper_proj/results/multi/'
    diagnostic_folder: '../pygna_paper_proj/results/multi/figures/'
    
topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 3
    cores: 1

association:
    analyse: []
    geneset_B : ''
    number_of_permutations: 3
    cores: 1

within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 3
    cores: 1

figures:
    extension: ['pdf', 'png']
    outpath: '../pygna_paper_proj/results/multi/figures/'

hdn_parameters:
    number_simulations: 2
    n_nodes: 10
    network_probability: []
    hdn_probability: []
    hdn_percentage: []

sbm_parameters:
    number_simulations: 2
    n_nodes: 10
    theta0: ''
    percentage: ''
    density: ''
    