parameters:
    network_file: 'data_tcga_workflow/external/biogrid_3.168_filtered.tsv'
    sp_matrix: "data_tcga_workflow/external/matrices/interactome_sp.hdf5"
    rwr_matrix: "data_tcga_workflow/external/matrices/interactome_rwr.hdf5"
    geneset_file: 'data_tcga_workflow/external/bailey.gmt'
    diagnostic_folder: 'data_tcga_workflow/diagnostic/'
    outpath: 'data_tcga_workflow/results_paper/'
    tcga_dataset: ["tcga_brca", "tcga_prad", "tcga_lusc", "tcga_laml", "tcga_dlbc", "tcga_blca"]

topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 2
    cores: 1

association:
    analyse: ['rwr', 'sp']
    geneset_B : 'data_tcga_workflow/external/goslim_entrez.gmt'
    number_of_permutations: 2
    cores: 1

within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 2
    cores: 1

figures:
    extension: ['png']
    outpath: 'figures/'
