parameters:
    network_file: '../dataset-pygna-workflow-results/data/external/biogrid_3.168_filtered.tsv'
    sp_matrix: "../dataset-pygna-workflow-results/data/external/matrices/interactome_sp.hdf5"
    rwr_matrix: "../dataset-pygna-workflow-results/data/external/matrices/interactome_rwr.hdf5"
    geneset_file: '../dataset-pygna-workflow-results/data/external/bailey.gmt'
    diagnostic_folder: '../dataset-pygna-workflow-results/data/processed/temp/figures/'
    outpath: '../dataset-pygna-workflow-results/data/processed/temp/datasets/'
    tcga_dataset: ["tcga_brca", "tcga_prad", "tcga_lusc", "tcga_laml", "tcga_dlbc", "tcga_blca"]#, "tcga_lcml"]

topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 1000
    cores: 4

association:
    analyse: ['rwr', 'sp']
    geneset_B : '../dataset-pygna-workflow-results/data/external/goslim_entrez.gmt'
    number_of_permutations: 1000
    cores: 4

within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 1000
    cores: 16

figures:
    extension: ['png']
    outpath: 'figures/'
