parameters:
    network_file : '../pygna_paper_proj/data/external/biogrid_3.168_filtered.tsv'
    sp_matrix: "../pygna_paper_proj/data/interactome_SP.hdf5"
    rwr_matrix: "../pygna_paper_proj/data/interactome_RWR.hdf5"
    geneset_file: '../pygna_paper_proj/data/external/bailey.gmt'
    geneset_csv: ''
    diagnostic_folder: '../pygna_paper_proj/results/multi/figures/'
    outpath: '../pygna_paper_proj/results/multi/'
    tcga_dataset: ["TCGA-BRCA", "TCGA-BLCA"]

topology:
    analyse: ['module','internal_degree','total_degree','rwr', 'sp']
    number_of_permutations: 100
    cores: 4

association:
    analyse: ['rwr', 'sp']
    geneset_B : '../pygna_pipeline/data/disgenet_cancer_groups_testing.gmt'
    number_of_permutations: 100
    cores: 4

within_comparison:
    analyse: ['rwr', 'sp']
    number_of_permutations: 100
    cores: 4

figures:
    extension: ['png']
    outpath: '../pygna_pipeline/results/figures/'
