configfile: "config.yaml"
report: "report/workflow.rst"

# Full GNT analysis parameters
NETWORK = config["analysis_full"]["network_file"]
GENESET = config["analysis_full"]["geneset_file"]
OUTPUT_FOLDER = config["analysis_full"]["outpath"]
PREFIX = config["analysis_full"]["prefix"]
NOP = config["analysis_full"]["number_of_permutations"]
CORES = config["analysis_full"]["cores"]
GENESET_B = config["analysis_full"]["geneset_B"]


# If the matrices for the full analysis are not specified, they are generated by the rule
if len(config["analysis_full"]["sp_matrix"]) > 0:
    SP_MATRIX = config["analysis_full"]["sp_matrix"]
else:
    SP_MATRIX = OUTPUT_FOLDER + PREFIX + "_sp_matrix.hdf5"

if len(config["analysis_full"]["rwr_matrix"]) > 0:
    RWR_MATRIX = config["analysis_full"]["rwr_matrix"]
else:
    RWR_MATRIX = OUTPUT_FOLDER + PREFIX + "_rwr_matrix.hdf5"

include: "rules/pygna.smk"

rule GNT_all:
    input:
        OUTPUT_FOLDER+PREFIX+"_table_internal_degree.csv",
        OUTPUT_FOLDER+PREFIX+"_table_total_degree.csv",
        OUTPUT_FOLDER+PREFIX+"_table_module.csv",
        OUTPUT_FOLDER+PREFIX+"_table_RW.csv",      
        OUTPUT_FOLDER+PREFIX+"_table_SP.csv"
        

rule GNA_association_all:
    input:
        OUTPUT_FOLDER+PREFIX+"_table_association_rwr.csv",
        OUTPUT_FOLDER+PREFIX+"_table_association_sp.csv"

rule GNA_comparison_all:
    input:
        OUTPUT_FOLDER+PREFIX+"_table_comparison_rwr.csv",
        OUTPUT_FOLDER+PREFIX+"_table_comparison_sp.csv"
