---
title: "R Notebook"
output: html_notebook
---
Initial definitions
```{r}
requiredPackages = c("BiocManager","SummarizedExperiment", "TCGAbiolinks", "org.Hs.eg.db", "recount", "TCGAutils", "limma", "biomaRt")
for(p in requiredPackages){
  if(!require(p,character.only = TRUE)) {
    res = tryCatch({
      install.packages(p)  
    }, error = function(e) {
      BiocManager::install(p) 
    })
  }
  library(p,character.only = TRUE)
}
convert.ENSG.Symbol<-function(genes){
  mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
  G_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id","hgnc_symbol"),values=genes,mart= mart)
  #merge(DEG.ucs,G_list,by.x="gene",by.y="ensembl_gene_id")
  return(G_list)
}

getTissue <-function(project) {
  tissue = NULL
  switch (project,
    "TCGA-DLBC" ={tissue ="blood"},    #Lymphoma
    "TCGA-LUSC" ={tissue ="lung"},     #Lung
    "TCGA-LAML" ={tissue ="blood"},    #Leukemia
    "TCGA-LCML" ={tissue ="blood"},    #Myelogenous Leukemia
    "TCGA-PRAD" ={tissue ="prostate"}, #Prostate
    "TCGA-BRCA" ={tissue ="breast"}    #Breast
    )
  return(tissue)
}

PROJECT="TCGA-BRCA"
tissue=getTissue(PROJECT)
GTEX = paste("GTEX_",tissue,sep="")
TCGA = paste("TCGA_",tissue,sep="")
alternate = c("TCGA-DLBC","TCGA-LAML","TCGA-LCML", "TCGA-LUSC")
```


Common init
```{r}
print(PROJECT)
# Start the elaboration on TCGA (there are only tumor samples)
print("Downloading data from TCGA")
query<- GDCquery(project = PROJECT,
                 data.category = "Transcriptome Profiling",
                 data.type = "Gene Expression Quantification",
                 workflow.type = "HTSeq - Counts")
GDCdownload(query)
experiment <- GDCprepare(query = query)
eset.tcga.cancer = assay(experiment)
```
If Project in alternate - download
```{r}
  print("No normal-tissue from TCGA: downloading data from GTEX")
  ucs.recount.gtex<-TCGAquery_recount2(project="GTEX", tissue=tissue)
  SE.ucs.recount.gtex <- ucs.recount.gtex[[GTEX]]
  eset.gtex<-assays(scale_counts(ucs.recount.gtex[[GTEX]], round = TRUE))$counts
```

elaborate part
```{r}

  rse_scaled <- scale_counts(ucs.recount.gtex[[GTEX]], round = TRUE)
  rownames(eset.gtex) <- gsub("\\..*", "", rownames(eset.gtex))
  ##merging data by row names
  print("Performing data preparaton")
  dataPrep.ucs<-merge(as.data.frame(eset.gtex), as.data.frame(eset.tcga.cancer), by=0)
  rownames(dataPrep.ucs)<-dataPrep.ucs$Row.names
  dataPrep.ucs$Row.names<-NULL
  print("Performing data normalization")
  dataNorm.ucs <- TCGAanalyze_Normalization(tabDF = dataPrep.ucs,
                                            geneInfo = geneInfoHT)
  print("Performing data filtering")
  dataFilt.ucs <- TCGAanalyze_Filtering(tabDF = dataNorm.ucs,
                                        method = "quantile", 
                                        qnt.cut =  0.25)
  print("Performing DEA")
  DEG.ucs <- TCGAanalyze_DEA( mat1 = dataFilt.ucs[,colnames(eset.gtex)],
                              mat2 = dataFilt.ucs[,colnames(eset.tcga.cancer)],
                              Cond1type = "Normal",
                              Cond2type = "Tumor",
                              fdr.cut = 1 ,
                              logFC.cut = 0,
                              method = "glmLRT")
```

Else.... 
```{r}
  print("Normal tissue found in TCGA")
  print("Performing data normalization")
  dataNorm <- TCGAanalyze_Normalization(tabDF = eset.tcga.cancer, geneInfo =  geneInfoHT)
  print("Performing data filtering")
  dataFilt <- TCGAanalyze_Filtering(tabDF = dataNorm,method = "quantile",qnt.cut =  0.25)
  print("Performing DEA")
  samplesNT <- TCGAquery_SampleTypes(barcode = colnames(dataFilt),typesample = c("NT"))
  samplesTP <- TCGAquery_SampleTypes(barcode = colnames(dataFilt),typesample = c("TP"))
  DEG.ucs2 <- TCGAanalyze_DEA(mat1 = dataFilt[,samplesNT],
                              mat2 = dataFilt[,samplesTP],
                              Cond1type = "Normal",
                              Cond2type = "Tumor",
                              fdr.cut = 1,
                              logFC.cut = 0,
                              method = "glmLRT")
```